# Generated by Django 5.1.3 on 2024-11-29 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('continent', 'Continent'), ('country', 'Country'), ('state', 'State'), ('city', 'City')], max_length=20)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('state_abbr', models.CharField(blank=True, max_length=3, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='location.location')),
            ],
        ),
    ]
