# Generated by Django 5.1.3 on 2024-12-02 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_all_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='center',
        ),
    ]
