# Generated by Django 5.1.3 on 2024-12-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_accommodation_delete_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='center',
        ),
        migrations.AlterField(
            model_name='all_location',
            name='center',
            field=models.CharField(max_length=100),
        ),
    ]
