# Generated by Django 5.1.3 on 2024-12-02 11:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_remove_accommodation_center_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_location',
            name='center',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
