# Generated by Django 5.1.3 on 2024-12-02 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_alter_all_location_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_location',
            name='center',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='LocalizeAccommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('bn', 'Bengali')], max_length=2)),
                ('description', models.TextField()),
                ('policy', models.JSONField(default=dict)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizations', to='location.accommodation')),
            ],
        ),
    ]
