# Generated by Django 5.1.3 on 2024-12-02 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_alter_all_location_center_localizeaccommodation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizeaccommodation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='localizeaccommodation',
            name='policy',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localizeaccommodation',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localized', to='location.accommodation'),
        ),
    ]
