# Generated by Django 5.1.3 on 2024-12-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_alter_localizeaccommodation_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aaa', models.PositiveSmallIntegerField(default=0)),
                ('bbb', models.CharField(max_length=100)),
                ('ccc', models.CharField(max_length=2)),
                ('ddd', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='LocalizeAccommodation',
        ),
    ]
