# Generated by Django 5.1.3 on 2024-12-02 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0011_localize_delete_localizeaccommodation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalizeAccommodation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('en', 'English'), ('bn', 'Bengali')], max_length=2)),
                ('description', models.TextField()),
                ('policy', models.JSONField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localized', to='location.accommodation')),
            ],
        ),
    ]
